CREATE TABLE IF NOT EXISTS couples (
  id TEXT PRIMARY KEY, code TEXT UNIQUE, seq INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS members (
  token_hash TEXT PRIMARY KEY, couple TEXT NOT NULL, member TEXT NOT NULL, created INTEGER NOT NULL,
  UNIQUE (couple, member)
);
CREATE TABLE IF NOT EXISTS rec (
  couple TEXT NOT NULL, id TEXT NOT NULL, kind TEXT NOT NULL, data TEXT NOT NULL,
  u INTEGER NOT NULL, del INTEGER NOT NULL DEFAULT 0, seq INTEGER NOT NULL,
  PRIMARY KEY (couple, id)
);
CREATE INDEX IF NOT EXISTS rec_seq ON rec (couple, seq);
CREATE TABLE IF NOT EXISTS digests (
  couple TEXT NOT NULL, day TEXT NOT NULL, seq INTEGER NOT NULL, at INTEGER NOT NULL, json TEXT NOT NULL,
  PRIMARY KEY (couple, day)
);
CREATE TABLE IF NOT EXISTS usage (
  couple TEXT NOT NULL, day TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (couple, day)
);
